version: '3.9'

services:
  nats-server:
    image: nats:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: core-dev
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    command: -js
